#!/usr/bin/env python3
"""
export_to_onnx.py — Export a YOLO26 .pt model to ONNX for the AMB Pro2 NPU.

This script:
  1. Loads a trained YOLO26 PyTorch model (.pt)
  2. Exports it to ONNX with AMB Pro2-specific settings:
       - opset=12 (NPU-compatible)
       - simplify=True (removes unnecessary graph nodes)
       - dynamic=False (fixed input size required by NPU)
  3. Optionally generates a calibration dataset.txt from validation images
  4. Copies everything into a self-contained conversion workspace

Usage:
    python3 export_to_onnx.py                           # uses defaults
    python3 export_to_onnx.py --weights best.pt --imgsz 416
    python3 export_to_onnx.py --weights best.pt --imgsz 416 --gen-dataset --dataset-dir ./valid/images
"""

import argparse
import os
import sys
import shutil
import glob


def export_onnx(weights: str, imgsz: int, opset: int, output_dir: str):
    """Export a YOLO26 .pt model to ONNX format."""
    try:
        from ultralytics import YOLO
    except ImportError:
        print("[ERROR] ultralytics is not installed. Run: pip install ultralytics")
        sys.exit(1)

    weights = os.path.abspath(weights)
    if not os.path.isfile(weights):
        print(f"[ERROR] Weights file not found: {weights}")
        sys.exit(1)

    print(f"[1/3] Loading model: {weights}")
    model = YOLO(weights)

    print(f"[2/3] Exporting to ONNX (opset={opset}, imgsz={imgsz}, simplify=True, dynamic=False)")
    onnx_path = model.export(
        format="onnx",
        opset=opset,
        simplify=True,
        dynamic=False,
        imgsz=imgsz,
    )

    if not onnx_path or not os.path.isfile(str(onnx_path)):
        # Ultralytics puts the .onnx next to the .pt
        onnx_path = weights.replace(".pt", ".onnx")

    if not os.path.isfile(onnx_path):
        print("[ERROR] ONNX export failed — output file not found.")
        sys.exit(1)

    # Copy to output directory
    os.makedirs(output_dir, exist_ok=True)
    dst = os.path.join(output_dir, os.path.basename(onnx_path))
    if os.path.abspath(onnx_path) != os.path.abspath(dst):
        shutil.copy2(onnx_path, dst)

    print(f"[3/3] ONNX model saved to: {dst}")
    print(f"      Size: {os.path.getsize(dst) / 1024 / 1024:.1f} MB")
    return dst


def generate_dataset_txt(image_dir: str, output_dir: str, max_images: int = 200):
    """Generate a dataset.txt file listing calibration images (one per line)."""
    if not os.path.isdir(image_dir):
        print(f"[WARN] Image directory not found: {image_dir}")
        return None

    extensions = ("*.jpg", "*.jpeg", "*.png", "*.bmp")
    image_files = []
    for ext in extensions:
        image_files.extend(glob.glob(os.path.join(image_dir, ext)))
        image_files.extend(glob.glob(os.path.join(image_dir, ext.upper())))

    if not image_files:
        print(f"[WARN] No images found in: {image_dir}")
        return None

    image_files = sorted(image_files)[:max_images]

    # Copy images to output dir
    images_out = os.path.join(output_dir, "images")
    os.makedirs(images_out, exist_ok=True)
    for src in image_files:
        dst = os.path.join(images_out, os.path.basename(src))
        if not os.path.exists(dst):
            shutil.copy2(src, dst)

    # Write dataset.txt with relative paths
    dataset_txt = os.path.join(output_dir, "dataset.txt")
    with open(dataset_txt, "w") as f:
        for src in image_files:
            f.write(f"images/{os.path.basename(src)}\n")

    print(f"[INFO] dataset.txt created with {len(image_files)} images → {dataset_txt}")
    return dataset_txt


def generate_inputmeta_yml(output_dir: str, imgsz: int, model_name: str = "best"):
    """Generate the _inputmeta.yml file for the Acuity toolchain."""
    yml_path = os.path.join(output_dir, f"{model_name}_inputmeta.yml")

    # Detect the ONNX input layer name (default for YOLO26 is "images")
    input_layer_id = "images"
    onnx_path = os.path.join(output_dir, f"{model_name}.onnx")
    if os.path.isfile(onnx_path):
        try:
            import onnx
            m = onnx.load(onnx_path)
            if m.graph.input:
                input_layer_id = m.graph.input[0].name
                print(f"[INFO] Detected ONNX input layer name: {input_layer_id}")
        except Exception:
            pass  # fall back to "images"

    # Acuity appends a suffix like "_392" to layer IDs — we generate both forms
    # The user may need to update the lid after running `pegasus import`
    content = f"""# !!!This file disallow TABs!!!
# Auto-generated by export_to_onnx.py for AMB Pro2 NPU
# Input: RGB {imgsz}x{imgsz}, normalized to [0, 1] (scale=1/255)
input_meta:
  databases:
  - path: dataset.txt
    type: TEXT
    ports:
    - lid: {input_layer_id}
      category: image
      dtype: float32
      sparse: false
      tensor_name:
      layout: nchw
      shape:
      - 1
      - 3
      - {imgsz}
      - {imgsz}
      fitting: scale
      preprocess:
        reverse_channel: true
        mean:
        - 0
        - 0
        - 0
        scale: 1.0
        preproc_node_params:
          add_preproc_node: false
          preproc_type: IMAGE_RGB
          preproc_image_size:
          - {imgsz}
          - {imgsz}
          preproc_crop:
            enable_preproc_crop: false
            crop_rect:
            - 0
            - 0
            - {imgsz}
            - {imgsz}
          preproc_perm:
          - 0
          - 1
          - 2
          - 3
      redirect_to_output: false
"""
    with open(yml_path, "w") as f:
        f.write(content)

    print(f"[INFO] Input meta written to: {yml_path}")
    return yml_path


def main():
    # models/weights/best.pt is the canonical model: a stripped yolo26n checkpoint that
    # measured mAP@.5 = 0.336 on the validation set, against 0.285 for the older
    # YOLO26_Training run (since removed).
    default_weights = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..", "weights", "best.pt"
    )

    parser = argparse.ArgumentParser(
        description="Export YOLO26 .pt to ONNX for AMB Pro2 NPU"
    )
    parser.add_argument(
        "--weights", type=str, default=default_weights,
        help="Path to the trained .pt weights file"
    )
    parser.add_argument(
        "--imgsz", type=int, default=416,
        help="Input image size (must match firmware NN_WIDTH/NN_HEIGHT, default: 416)"
    )
    parser.add_argument(
        "--opset", type=int, default=12,
        help="ONNX opset version (AMB Pro2 NPU supports 12 best, default: 12)"
    )
    parser.add_argument(
        "--output-dir", type=str, default=None,
        help="Output directory for conversion workspace (default: ./conversion_workspace)"
    )
    parser.add_argument(
        "--gen-dataset", action="store_true",
        help="Generate calibration dataset.txt from validation images"
    )
    parser.add_argument(
        "--dataset-dir", type=str, default=None,
        help="Directory containing calibration images (used with --gen-dataset)"
    )
    parser.add_argument(
        "--max-images", type=int, default=200,
        help="Maximum number of calibration images (default: 200)"
    )
    parser.add_argument(
        "--model-name", type=str, default="best",
        help="Model name used for output files (default: best)"
    )

    args = parser.parse_args()

    if args.output_dir is None:
        args.output_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "conversion_workspace")

    if args.dataset_dir is None:
        args.dataset_dir = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..", "dataset", "valid", "images"
        )

    print("=" * 60)
    print("  YOLO26 → ONNX Export for AMB Pro2")
    print("=" * 60)
    print(f"  Weights:     {args.weights}")
    print(f"  Image size:  {args.imgsz}×{args.imgsz}")
    print(f"  Opset:       {args.opset}")
    print(f"  Output dir:  {args.output_dir}")
    print(f"  Model name:  {args.model_name}")
    print("=" * 60)

    # Step 1: Export to ONNX
    onnx_path = export_onnx(args.weights, args.imgsz, args.opset, args.output_dir)

    # Rename if model_name differs from filename
    expected_name = f"{args.model_name}.onnx"
    actual_name = os.path.basename(onnx_path)
    if actual_name != expected_name:
        new_path = os.path.join(args.output_dir, expected_name)
        shutil.copy2(onnx_path, new_path)
        onnx_path = new_path

    # Step 2: Generate calibration dataset
    if args.gen_dataset:
        generate_dataset_txt(args.dataset_dir, args.output_dir, args.max_images)

    # Step 3: Generate input meta YAML
    generate_inputmeta_yml(args.output_dir, args.imgsz, args.model_name)

    print()
    print("=" * 60)
    print("  Export complete!")
    print("=" * 60)
    print(f"  ONNX model:   {onnx_path}")
    print(f"  Workspace:    {args.output_dir}")
    print()
    print("  Next steps:")
    print("    1. Review the _inputmeta.yml (update 'lid' if needed after pegasus import)")
    print("    2. Run convert_to_nb.sh to quantize and generate the .nb binary")
    print("    3. Flash the .nb file to the AMB Pro2 board")
    print("=" * 60)


if __name__ == "__main__":
    main()
